# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
server:
  port: 10000

spring:
  application:
    name: ufc
  web:
    resources:
      add-mappings: true

# 이하는 개발환경 전용 세팅 - 배포시 삭제
  # datasource:
  #   driver-class-name: com.mysql.cj.jdbc.Driver
  #   url: jdbc:mysql://localhost:3306/ufc?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
  #   username: root
  #   password: root
  # jpa:
  #   hibernate:
  #     ddl-auto: none
  #   properties:
  #     hibernate:
  #       dialect: org.hibernate.dialect.MySQL8Dialect
  #       format_sql: true
  #   show-sql: true


#swagger?
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#swagger
# springdoc:
#   api-docs:
#     path: /v3/api-docs
